### ISSUE TITLE
Right-click on "dse" =no "run" option

### ISSUE THREAD

**Issue by JohnSandel** [KenHarkey/dse#19]
Thank you for a promising GUI. Followed your steps in Freya 0.3.2:

- ran "sudo apt-get install wget gjs" 
- DLed
- extracted

… but a right-click on the only extracted file labeled solely "dse" (the program) has no "run" option (nor do any of the others).

What am I missing? 

Can you specify the folders to which I should move your extracted components?

Thanks in advance.

**Comment by bil-elmoussaoui** [comment]
`chmod +x dse`

**Comment by JohnSandel** [comment]
Thank you, Bilal.

**Comment by bil-elmoussaoui** [comment]
@JohnSandel You can close this :)
