### ISSUE TITLE
a few ideas of cool things I would like to see added someday...

### ISSUE THREAD

**Issue by OpnSrcConstruction** [KenHarkey/dse#3]
A few ideas for your cool project 
there is a hack to get hulu working on Ubuntu
www.omgubuntu.co.uk/2015/09/how-to-watch-hulu-on-ubuntu-1404-up
~Spotify
~PlayOnLinux 
~Chrome(official/beta)
~Veracrypt(trueCrypt-successor)
~LightWorks(Community_edition)
~SimpleScreenRecorder
~obs(open-broadcast-system)

**Comment by KenHarkey** [comment]
chrome is already included, I am staying mostly with stable versions for....stability but i'll add the majority of your requested apps eventually.
