### ISSUE TITLE
a few things I would like to be added

### ISSUE THREAD

**Issue by sergiuprt** [KenHarkey/dse#4]
*Arduino IDE
*Visul Studio Code
*OS X fonts
*Corebird
*Clementine
*Gnome System Monitor
*Conky

**Comment by KenHarkey** [comment]
Visual studio code is already installed, please check the changelog or run the app for currently supported software before opening an issue next time

**Comment by bil-elmoussaoui** [comment]
@KenHarkey Please don't install the ppa version :( this version is really outdated!

**Comment by KenHarkey** [comment]
@bil-elmoussaoui you mean of arduino?  I'll change it when i get a chance

**Comment by sergiuprt** [comment]
yeah, arduino. get the version 1.6.6 :)

**Comment by KenHarkey** [comment]
Ah yes, the versionin the repo is 1.0.5  I'm making some changes to the app, after i'm done i'll look into that as well as a few other things.
