### ISSUE TITLE
Do not remove files

### ISSUE THREAD

**Issue by bil-elmoussaoui** [KenHarkey/dse#8]
I think you should add a condition if the file exists before using `rm $FILE`in install.sh :+1:

**Comment by KenHarkey** [comment]
@bil-elmoussaoui which plugin uses rm $FILE?

**Comment by bil-elmoussaoui** [comment]
Arduino

**Comment by KenHarkey** [comment]
ok, it was arduino and visual studio code, it's been fixed and pushed :v:
